stages:
  - build
  - test

# this job 
# - prepares the environment
#   (pulls required docker containers, clones and builds inet)
# - builds the simulte project itself
Build:
  stage: build
  variables:
    RV: 'rover-main/scripts'
    INETBRANCH: 'master'     # needs to be switched to v4.3.0 or similar as soon as available
    #INETBRANCH: 'v4.2.1'
  script:
    - "mkdir .tmp"
    - "mv * .tmp"
    - "git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@sam-dev.cs.hm.edu/rover/rover-main.git"
    # - "$RV/pull_images.sh"
    - "mv .tmp simulte"
    - "git clone --branch ${INETBRANCH} https://gitlab-ci-token:${CI_JOB_TOKEN}@sam-dev.cs.hm.edu/rover/inet.git inet4"
    - "cd inet4"
    - "../$RV/omnetpp exec make makefiles"
    - "../$RV/omnetpp exec make -j16; TEST_STATUS=${PIPESTATUS[0]}"
    # we do not need the inet sources anymore - delete them to have less artifacts
    - "find . -name \"*.cc\" -type f -delete"
    # build simulte itself
    - "cd ../simulte"
    - "../$RV/omnetpp exec make makefiles"
    - "../$RV/omnetpp exec make -j16"
  artifacts:
    paths:
    # we keep the scripts
    - rover-main/scripts
    # we need to keep the ned files and the simulte lib
    - simulte
    # we need to keep the ned files and the inet lib (all stored in the src subfolder)
    - inet4/src
    expire_in: 2 weeks

# This job runs the fingerprint tests
Fingerprints:
  stage: test
  variables:
    RV: 'rover-main/scripts'
  script:
    # - "mv tests simulte/"
    - "cd simulte/tests/fingerprint"
    - "../../../$RV/omnetpp exec ./fingerprints"
  artifacts:
    paths:
    - simulte/tests/fingerprint
    expire_in: 2 weeks

